name: CI

on:
  workflow_dispatch:
    inputs:
      patch:
        description: "Patch"
        required: true
        type: string
        default: "true"
  push:
    branches: [develop]
    paths-ignore:
      - "docs/**"
      - ".github/**"
      - ".remarkrc"
      - ".gitignore"
      - "**.md"
      - "**.yml"
      - "**.json"
      - "!.github/workflows/main.yml"
      - "!data/**"
    tags: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Install dependencies
        run: |
          pip install vpk
          rm -f /home/runner/.local/bin/vpk
          sudo bash -c 'cat <<\EOF > /usr/local/bin/vpk
          #!/bin/bash
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          python "$GITHUB_WORKSPACE/$REPO_NAME/dev/vpk_cli.py" "${@}"
          EOF'
          sudo chmod +x /usr/local/bin/vpk
      - name: Check tag
        id: check-tag
        if: ${{ github.event_name == 'push' }}
        run: |
          if [[ ${{ github.event.ref }} == refs/tags/* ]]; then
            echo "release=true" >> $GITHUB_OUTPUT
          fi
      - name: Build mastercomfig (prerelease)
        run: dev/release.sh
        if: ${{ github.event_name == 'push' && steps.check-tag.outputs.release != 'true' }}
        env:
          prerelease: true
          GH_TOKEN: ${{secrets.REPO_TOKEN}}
      - name: Build mastercomfig (patch)
        run: dev/release.sh
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.patch == 'true' }}
        env:
          patch: true
          GH_TOKEN: ${{secrets.REPO_TOKEN}}
      - name: Build mastercomfig (release)
        run: dev/release.sh
        if: ${{ github.event_name == 'push' && steps.check-tag.outputs.release == 'true' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GH_TOKEN: ${{secrets.REPO_TOKEN}}
      - name: Build mastercomfig
        run: dev/package.sh
        if: ${{ github.event_name == 'pull_request' }}
